# Generated by Django 5.2.1 on 2025-05-28 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reading_level',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(default='', max_length=20000)),
                ('age_min', models.IntegerField(db_column='age_min', default=0)),
                ('age_max', models.IntegerField(db_column='age_max', default=100)),
            ],
        ),
        migrations.CreateModel(
            name='reading_prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_id', models.IntegerField(db_column='prompt_id', default=10)),
                ('prompt_body', models.CharField(default='Not Poulated', max_length=20000)),
                ('prompt_type', models.CharField(default='Not Poulated', max_length=20000)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryJinnator.reading_level')),
            ],
        ),
    ]
