# Generated by Django 5.2 on 2025-05-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0002_rename_prompt_prompts'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompts',
            name='text',
            field=models.CharField(default='Hello World', max_length=200),
        ),
        migrations.AddField(
            model_name='reading_levels',
            name='reading_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reading_levels',
            name='text',
            field=models.CharField(default='Hello World', max_length=200),
        ),
    ]
