# Generated by Django 5.2 on 2025-05-09 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0003_prompts_text_reading_levels_reading_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reading_level',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(default='', max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='reading_prompts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_body', models.CharField(default='Not Poulated', max_length=20000)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryJinnator.reading_level')),
            ],
        ),
    ]
