# Generated by Django 5.2 on 2025-05-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0004_reading_level_reading_prompts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prompts',
        ),
        migrations.DeleteModel(
            name='reading_levels',
        ),
    ]
