# Generated by Django 5.2 on 2025-05-09 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0005_delete_prompts_delete_reading_levels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reading_prompts',
            new_name='reading_prompt',
        ),
    ]
