# Generated by Django 5.2 on 2025-05-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0006_rename_reading_prompts_reading_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading_prompt',
            name='prompt_type',
            field=models.CharField(default='Not Poulated', max_length=20000),
        ),
    ]
