# Generated by Django 5.2 on 2025-05-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0007_reading_prompt_prompt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading_level',
            name='age_max',
            field=models.IntegerField(db_column='age_max', default=100),
        ),
        migrations.AddField(
            model_name='reading_level',
            name='age_min',
            field=models.IntegerField(db_column='age_min', default=0),
        ),
        migrations.AddField(
            model_name='reading_prompt',
            name='prompt_id',
            field=models.IntegerField(db_column='prompt_id', default=''),
        ),
    ]
