# Generated by Django 5.2 on 2025-05-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0008_reading_level_age_max_reading_level_age_min_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_prompt',
            name='prompt_id',
            field=models.IntegerField(db_column='prompt_id', default=1),
        ),
    ]
