# Generated by Django 5.2 on 2025-05-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0009_alter_reading_prompt_prompt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_prompt',
            name='prompt_id',
            field=models.IntegerField(db_column='prompt_id', default=10),
        ),
    ]
