# Generated by Django 5.2 on 2025-05-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0012_alter_reading_prompt_prompt_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading_level',
            old_name='age_max',
            new_name='max_age',
        ),
        migrations.RenameField(
            model_name='reading_level',
            old_name='age_min',
            new_name='min_age',
        ),
    ]
