# Generated by Django 5.2 on 2025-05-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0013_rename_age_max_reading_level_max_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_level',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='reading_level',
            name='min_age',
        ),
        migrations.AddField(
            model_name='reading_level',
            name='maximum_age',
            field=models.IntegerField(db_column='age_max', default=100),
        ),
        migrations.AddField(
            model_name='reading_level',
            name='minimum_age',
            field=models.IntegerField(db_column='age_min', default=0),
        ),
    ]
