# Generated by Django 5.2 on 2025-05-10 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0014_remove_reading_level_max_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_prompt',
            name='prompt_id',
            field=models.IntegerField(default=10),
        ),
    ]
