# Generated by Django 5.2 on 2025-05-10 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0015_alter_reading_prompt_prompt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_prompt',
            name='prompt_id',
        ),
    ]
