# Generated by Django 5.2 on 2025-05-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0016_remove_reading_prompt_prompt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_level',
            name='maximum_age',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='reading_level',
            name='minimum_age',
            field=models.IntegerField(default=0),
        ),
    ]
