# Generated by Django 5.2 on 2025-05-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0017_alter_reading_level_maximum_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_level',
            name='minimum_age',
            field=models.IntegerField(default=1),
        ),
    ]
