# Generated by Django 5.2 on 2025-05-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0018_alter_reading_level_minimum_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_level',
            name='maximum_age',
        ),
        migrations.RemoveField(
            model_name='reading_level',
            name='minimum_age',
        ),
    ]
