# Generated by Django 5.2 on 2025-05-10 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0019_remove_reading_level_maximum_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading_level',
            name='level_name',
            field=models.CharField(default='MyLevel-default', max_length=200),
        ),
        migrations.AlterField(
            model_name='reading_prompt',
            name='prompt_body',
            field=models.CharField(default='Not Poulated', max_length=200),
        ),
        migrations.AlterField(
            model_name='reading_prompt',
            name='prompt_type',
            field=models.CharField(default='Not Poulated', max_length=200),
        ),
    ]
