# Generated by Django 5.2 on 2025-05-10 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0020_alter_reading_level_level_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_prompt',
            name='level_id',
        ),
        migrations.DeleteModel(
            name='reading_level',
        ),
        migrations.DeleteModel(
            name='reading_prompt',
        ),
    ]
