# Generated by Django 5.2 on 2025-05-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0021_remove_reading_prompt_level_id_delete_reading_level_and_more'),
    ]

    operations = [
    ]
