# Generated by Django 5.2 on 2025-05-10 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StoryJinnator', '0022_auto_20250510_0418'),
    ]

    operations = [
        migrations.CreateModel(
            name='reading_level',
            fields=[
                ('level_id', models.IntegerField(primary_key=True, serialize=False)),
                ('level_name', models.CharField(default='MyLevel-default', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='reading_prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_body', models.CharField(default='Not Poulated', max_length=200)),
                ('prompt_type', models.CharField(default='Not Poulated', max_length=200)),
                ('level_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StoryJinnator.reading_level')),
            ],
        ),
    ]
