# Generated by Django 5.2 on 2025-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoryJinnator', '0023_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading_level',
            name='level_id',
        ),
        migrations.RemoveField(
            model_name='reading_prompt',
            name='level_id',
        ),
        migrations.AddField(
            model_name='reading_level',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
